# Generated by Django 3.0.5 on 2022-06-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBooks',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=50)),
                ('book_zone', models.CharField(max_length=30)),
                ('book_year', models.IntegerField(max_length=30)),
            ],
        ),
    ]
