# Generated by Django 3.0.5 on 2022-06-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addbooks',
            old_name='book_author',
            new_name='bookAuthor',
        ),
        migrations.RenameField(
            model_name='addbooks',
            old_name='book_id',
            new_name='bookId',
        ),
        migrations.RenameField(
            model_name='addbooks',
            old_name='book_name',
            new_name='bookName',
        ),
        migrations.RenameField(
            model_name='addbooks',
            old_name='book_year',
            new_name='bookYear',
        ),
        migrations.RenameField(
            model_name='addbooks',
            old_name='book_zone',
            new_name='bookZone',
        ),
    ]
