# Generated by Django 3.0.5 on 2022-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_auto_20220609_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='bookAuthor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='bookName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='bookYear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='bookZone',
            field=models.CharField(max_length=50),
        ),
    ]
